### ISSUE TITLE
Is it possible to make this work well with Routify SSR?

### ISSUE THREAD

**Issue by Evertt** [svelte-drama/suspense#2]
I just created an experiment with Routify and it seems that SSR doesn't work quite like you'd expect. It is possible to wait an arbitrary amount of time for SSR, but then on the client-side it will start the loading process from the beginning again. Which isn't a problem per se, but it means that sometimes it reverts already-loaded-DOM back to the loading-state.

[Here's a demo.](https://routify-suspend.vercel.app/) (You'll probably need to refresh a bunch of times to see what I mean.)

edit: hmm, wait, now I can't reproduce the problem anymore? Can you reproduce the problem when you load my demo?

**Comment by Evertt** [comment]
Never mind, I think it's working like it's supposed to, I can't reproduce the problem anymore.

**Comment by Evertt** [comment]
Oh nope, I found a way to reproduce the issue. Check the demo again. 😅 

[Here's my code](https://github.com/Evertt/routify-suspense/blob/main/src/pages/index.svelte)

**Comment by JamCart** [comment]
I have a few problems with this as a demo:
* No data is being passed from the server to client.  I would expect the client to have to start over from scratch if the data itself isn't hydrated.
* This is an issue you'd run in to just using Svelte's `{#await}` blocks.  Since that is the basis for this library, we're limited by its limitations.

If a demo manages to get past those two roadblocks, it might be worth another look.
